name: Build and Push Docker Images for Bicep

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_FE_IMAGENAME: "blazorappfe"
      DOCKER_BE_IMAGENAME: "webapibe"
      CONTAINER_REGISTRY_NAME: "**.azurecr.io"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Docker Image
        run: |
          cd src/Images/frontend/BlazorApp
          docker build -t ${{ env.CONTAINER_REGISTRY_NAME }}/${{ env.DOCKER_FE_IMAGENAME }}:latest .
          echo ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ env.CONTAINER_REGISTRY_NAME }} --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin
          docker push ${{ env.CONTAINER_REGISTRY_NAME }}/${{ env.DOCKER_FE_IMAGENAME }}:latest

      - name: Build and Push Backend Docker Image
        run: |
          cd src/Images/backend/WebAPI
          docker build -t ${{ env.CONTAINER_REGISTRY_NAME }}/${{ env.DOCKER_BE_IMAGENAME }}:latest .
          echo ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ env.CONTAINER_REGISTRY_NAME }} --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin
          docker push ${{ env.CONTAINER_REGISTRY_NAME }}/${{ env.DOCKER_BE_IMAGENAME }}:latest
